# Generated by Django 5.1.5 on 2025-02-14 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_electronicproduct_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad en existencia', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='musicproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad en existencia', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
