# Generated by Django 5.1.5 on 2025-02-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_electronicproduct_stock_musicproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='musicproduct',
            name='stock',
        ),
    ]
