# Generated by Django 5.1.5 on 2025-02-14 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_electronicproduct_stock_musicproduct_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='musicproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
