# Generated by Django 5.1.5 on 2025-02-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_electronicproduct_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
