# Generated by Django 5.1.5 on 2025-02-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_number',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
